# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-11 16:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_auto_20171003_0938'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('detalle', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'Departamento',
                'verbose_name_plural': 'Departamentos',
            },
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='precio_venta',
            new_name='precio_unidad',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='detalle',
        ),
    ]
