# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-11 17:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0004_pedido'),
    ]

    operations = [
        migrations.CreateModel(
            name='Envio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_articulo', models.IntegerField()),
                ('fecha_envio', models.DateTimeField()),
                ('numero_unidades', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Envio',
                'verbose_name_plural': 'Envio',
            },
        ),
    ]
