# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-31 05:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0005_envio'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='envio',
            options={'verbose_name': 'Envio', 'verbose_name_plural': 'Envios'},
        ),
        migrations.AddField(
            model_name='categoria',
            name='codigo',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
