# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-05 00:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0006_auto_20171031_0055'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detalle_Pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detalle_pedido', models.CharField(max_length=40)),
                ('estado', models.CharField(max_length=35)),
                ('fecha_pedido', models.DateTimeField()),
                ('precio', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Detalle_Pedido',
                'verbose_name_plural': 'Detalle_Pedidos',
            },
        ),
    ]
