# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-05 02:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0008_remove_detalle_pedido_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalle_pedido',
            name='fecha_pedido',
            field=models.DateTimeField(default=0),
        ),
        migrations.AlterField(
            model_name='envio',
            name='numero_unidades',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='precio',
            field=models.IntegerField(default=0),
        ),
    ]
