# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-05 22:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0010_detalle_pedido_pedido'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo_Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=35)),
            ],
            options={
                'verbose_name': 'Tipo_Producto',
                'verbose_name_plural': 'Tipo_Productos',
            },
        ),
    ]
